version: '3.8'

services:
  sk08-web:  # Změna názvu backendového kontejneru podle skupiny 8
    build:
      context: ./backend
    image: jansodomka/wea_semestralni_prace:backend
    ports:
      - "8007:8007"  # Změna portu pro backend na 8007
    volumes:
      - ./logs:/app/logs  # Mapování logů do lokálního adresáře logs
      - ./backend/app.db:/app/app.db  # Mapování SQLite databáze
    networks:
      - sk08-network  # Připojení k externí síti

  frontend:
    build:
      context: ./frontend
    image: jansodomka/wea_semestralni_prace:frontend
    ports:
      - "3000:3000"
    depends_on:
      - sk08-web  # Změněno podle nového názvu backendu
    networks:
      - sk08-network  # Připojení ke stejné síti jako backend

networks:
  sk08-network:
    external: true  # Registrace externí sítě
