version: '3.8'

services:
  sk08-web:  # Název kontejneru pro backend podle vaší skupiny
    container_name: sk08-web
    build:
      context: ./backend
    image: jansodomka/wea_semestralni_prace:backend
    ports:
      - "8007:3000"  # Exponovaný port 8007 pro backend
    volumes:
      - "/home/cerny/logs/sk08:/app/logs"  # Mapování logovací složky
    networks:
      - cdb-network  # Připojení k externí síti
      - internalnetwork
    depends_on:
      - mongo-db

  frontend:
    build:
      context: ./frontend
    image: jansodomka/wea_semestralni_prace:frontend
    ports:
      - "3000:3000"  # Exponovaný port 8008 pro frontend
    networks:
      - cdb-network  # Připojení k externí síti

  mongo-db:
    container_name: sk08-mongo
    image: mongo:latest  # Použijeme oficiální MongoDB image
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  # Root uživatel
      MONGO_INITDB_ROOT_PASSWORD: password  # Root heslo
    ports:
      - "27017:27017"  # Port MongoDB (default)
    volumes:
      - ./mongo-data:/data/db  # Místní úložiště dat, aby MongoDB data přežila restart kontejneru
    networks:
      - internalnetwork
  
  mongo-express:
    container_name: sk08-mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"  # Port where Mongo Express will be available
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin  # MongoDB admin username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password  # MongoDB admin password
      ME_CONFIG_MONGODB_SERVER: sk08-mongo  # The hostname of the MongoDB container
    depends_on:
      - mongo-db
    networks:
      - internalnetwork

networks:
  cdb-network:
    name: cdb-network
    driver: bridge
    external: true
  internalnetwork:
    name: internalnetwork
    driver: bridge
    external: false
